language: haskell

ghc:
    - 7.8
    - 7.6

install:
    - cabal install --enable-tests --only-dependencies -ftest-api liblastfm.cabal examples/liblastfm-examples.cabal

script:
    - cabal configure --enable-tests -ftest-api
    - cabal build
    - cabal test spec
    - cabal install liblastfm.cabal examples/liblastfm-examples.cabal
